### ISSUE TITLE
Conflicts with typogrify

### ISSUE THREAD

**Issue by jboynyc** [danielfrg/pelican-jupyter#30]
I had set `TYPOGRIFY = True` in my `pelicanconf.py` only to find that it breaks some functionality of ipynb posts. Specifcally, typogrify applies `<span>` elements to parts of the inline CSS, which ends up breaking those styles as well as MathJax. That is probably a bug in typogrify, but I thought I'd point it out here.

Obviously the easiest way to fix the issue is to disable typogrify.

**Comment by danielfrg** [comment]
Kinda tricky to fix for me since i don't use that plugin.

You can probably make it work with some extra CSS like I do for my theme: https://github.com/danielfrg/middle-theme/blob/master/templates/ipynb.css

**Comment by jboynyc** [comment]
Yeah, sorry to even open a ticket about this. It's not something that you need to worry about fixing, I think. I just thought this conflict should be documented in some way, because it cost me a while to figure out what was going wrong. Maybe adding a brief note in the README would do it.

**Comment by danielfrg** [comment]
Not a problem at all. I like to record this stuff in issues.

**Comment by dan-tee** [comment]
Thanks for opening the ticket. Spent some time trying to figure out why my strings don't get colored red. I found the weird <span>s inside color properties, but didn't know why.

Disabling Typogrify fixed it.
